export const GOAL_TYPES = {
  'GET_FIT': 'GET_FIT',
  'GET_STRONG': 'GET_STRONG',
  'EXERCISE': 'EXERCISE'
}

export const FIT_LEVEL = {
  BEGINNER: 'BEGINNER',
  INTERMEDIATE: 'INTERMEDIATE',
  ADVANCED: 'ADVANCED'
}